### ISSUE TITLE
代行がdoya大賞を受賞したときに名前が表示されない問題の修正

### ISSUE THREAD

**Issue by kiddykazz** [april-knights-dev/doya_bot#6]
https://aprilknights.slack.com/archives/CA798CMV0/p1598929200006200
代行が対象を取ったときに名前が表示されない問題が発生したため修正する

**Comment by Khiroka** [comment]
直した

<img width="665" alt="スクリーンショット 2020-09-26 13 09 28" src="https://user-images.githubusercontent.com/29135359/94329853-95008400-fff9-11ea-86ef-b0782cf9bad4.png">

**Comment by kiddykazz** [comment]
OKです
